### ISSUE TITLE
Missing property name for required fields

### ISSUE THREAD

**Issue by albertoleal** [iclanzan/jassi#3]
Hi,

I'm running some testes locally and I can see that the property value is empty for required fields, and I'm wondering why. 

thanks!

``` javascript
[
 { property: '',
    message: 'Required property "firstName" is missing.' },
  { property: '',
    message: 'Required property "lastName" is missing.' },
  { property: 'age',
    message: 'The instance must have a minimum value of 10.' }
 ]
```

**Comment by iclanzan** [comment]
The `property` value indicates where in the object the error in validation occurred. In your case `firstName` was expected on the root of the object, that’s why `property` is empty.

Let’s say you have this object:

```
{
  user: {
    name: {}
  }
}
```

If inside `name` you expect a `firstName` then the validation error’s `property` would be `user.name`.

Does that make sense?

**Comment by albertoleal** [comment]
Great, @iclanzan ! Thanks =)
